<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.5.0</VersionPrefix>
    <NeutralLanguage>en</NeutralLanguage>
    <SatelliteResourceLanguages>fr</SatelliteResourceLanguages>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <WarningsAsErrors>$(WarningsAsErrors);CA1304;CA1305;CA1307;CA1309;CA1310;CA1311</WarningsAsErrors>
  </PropertyGroup>
</Project>
